// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy9VFtzSmnNLyGr2LWRHLGw-f-uCAwQV0',
    appId: '1:357344415846:web:48d5b0d3cb3b9b82709da7',
    messagingSenderId: '357344415846',
    projectId: 'mynotes-flutter-project-ozgun',
    authDomain: 'mynotes-flutter-project-ozgun.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-ozgun.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWRhEVivsG6k8gsLbtXxaNCOk4YWLcP7I',
    appId: '1:357344415846:android:98ea926681095eb1709da7',
    messagingSenderId: '357344415846',
    projectId: 'mynotes-flutter-project-ozgun',
    storageBucket: 'mynotes-flutter-project-ozgun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG-8RQm7sabE5L-bxOm5NG3kXv-DyQxYs',
    appId: '1:357344415846:ios:c00007be0a014e95709da7',
    messagingSenderId: '357344415846',
    projectId: 'mynotes-flutter-project-ozgun',
    storageBucket: 'mynotes-flutter-project-ozgun.appspot.com',
    iosClientId: '357344415846-kt486l3ov7bgi1tichbrt9mg5qq4rd7c.apps.googleusercontent.com',
    iosBundleId: 'com.vimotto.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG-8RQm7sabE5L-bxOm5NG3kXv-DyQxYs',
    appId: '1:357344415846:ios:c00007be0a014e95709da7',
    messagingSenderId: '357344415846',
    projectId: 'mynotes-flutter-project-ozgun',
    storageBucket: 'mynotes-flutter-project-ozgun.appspot.com',
    iosClientId: '357344415846-kt486l3ov7bgi1tichbrt9mg5qq4rd7c.apps.googleusercontent.com',
    iosBundleId: 'com.vimotto.mynotes',
  );
}
